name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    if: github.repository == 'apache/incubator-pekko-http-quickstart-scala.g8'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.17

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: sbt & Paradox
        run: sbt test docs/paradox

      - name: generate and test, Scala 3
        run: |-
          sbt new file://$PWD --name=hello-world --scala_version=3.3.1 --force && pushd hello-world &&  sbt test
